services:
  fos_user.util.user_manipulator:
        class: UFT\UserBundle\Util\UserManipulator
        arguments: ['@fos_user.user_manager']
  uft_user.evente_listener.authentication_failure_event_listener:
        class: UFT\UserBundle\EventListener\AuthenticationFailureListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_subscriber, event: security.interactive_login, method: onAuthenticationSuccess  }
            - { name: kernel.event_listener, event: kernel.exception, method: onAuthenticationFailure  }
  slu.utils.relatoriosql:
      class: UFT\SluBundle\Util\RelatorioSQL
      arguments: ["@doctrine.orm.db2_entity_manager", "@service_container"]
  id_store:
      class: UFT\UserBundle\Store\IdStore
      arguments:
          - "@=service('doctrine').getManager()"
          - "@lightsaml.system.time_provider"

  user.usuario_attribute_mapper:
      class: UFT\UserBundle\Security\Service\UsuarioAttributeMapper

  user_creator:
      class: UFT\UserBundle\Security\User\UserCreator
      arguments:
         - "@=service('doctrine').getManager()"
         - "@lightsaml_sp.username_mapper.simple"
         - "@user.usuario_attribute_mapper"

  acme.logout_handler:
      class: UFT\UserBundle\Security\Lib\SamlLogoutHandler
      calls:
         - [setContainer, ["@service_container"]]

  security.authentication.listener.lightsaml_sp:
      class: UFT\UserBundle\Security\Firewall\LightSamlSpListener
      parent: security.authentication.listener.abstract
      abstract: true
      public: true
      calls:
        - [setProfile, ["@ligthsaml.profile.acs"]]

  login.error_handler:
      class: UFT\UserBundle\Security\Lib\SamlLoginErrorHandler
      calls:
         - [setContainer, ["@service_container"]]
